#!/bin/bash
# Copyright(c) 2021 Blacknon. All rights reserved.
# Use of this source code is governed by an MIT license
# that can be found in the LICENSE file.

export PYTHONIOENCODING='UTF-8'

# editor
export EDITOR='vim'

# color code
export COLOR_RED=$'\E[0;31m'
export COLOR_GREEN=$'\E[0;32m'
export COLOR_ORANGE=$'\E[0;33m'
export COLOR_BLUE=$'\E[0;34m'
export COLOR_PURPLE=$'\E[0;35m'
export COLOR_CYAN=$'\E[0;36m'
export COLOR_LGRAY=$'\E[0;37m'
export COLOR_DGRAY=$'\E[1;30m'
export COLOR_LRED=$'\E[1;31m'
export COLOR_LGREEN=$'\E[1;32m'
export COLOR_YELLOW=$'\E[1;33m'
export COLOR_LBLUE=$'\E[1;34m'
export COLOR_LPURPLE=$'\E[1;35m'
export COLOR_LCYAN=$'\E[1;36m'
export COLOR_WHITE=$'\E[1;37m'
export COLOR_NONE=$'\E[0m'

# man set color
export LESS_TERMCAP_mb=${COLOR_LRED}
export LESS_TERMCAP_md=${COLOR_PURPLE}
export LESS_TERMCAP_me=${COLOR_NONE}
export LESS_TERMCAP_se=${COLOR_NONE}
export LESS_TERMCAP_so=$'\E[01;44;32m'
export LESS_TERMCAP_ue=${COLOR_NONE}
export LESS_TERMCAP_us=${COLOR_YELLOW}

# less
export LESS=-R # lessでスクロールが効くようにする

# bat
export BAT_PAGER="less -RF" # batのpagerを設定

# PATH
export GOPATH=~/_go
case ${OSTYPE} in
darwin*)
  export GOROOT=/usr/local/opt/go/libexec
  export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:~/bin
  export PATH=$PATH:~/dotfiles/AppleScripts
  export PATH=/usr/local/opt/ncurses/bin:$PATH
  export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
  export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/ncurses/lib/
  export LDFLAGS=" -L/usr/local/opt/ncurses/lib"
  export CPPFLAGS=" -I/usr/local/opt/ncurses/include"
  export LDFLAGS=$LDFLAGS" -L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS=$CPPFLAGS" -I/usr/local/opt/openssl@0.1/include"
  ;;
linux*)
  export PATH=$PATH:$GOPATH/bin:~/bin
  export PATH=$PATH:/usr/local/go/bin
  ;;
esac
export PATH=$PATH:~/.cargo/bin            # Rust(Cargo)用PATH
export PATH=$PATH:~/.gem/ruby/bin         # Ruby gem用PATH
export PATH=$PATH:~/.nodebrew/current/bin # NodeJS用PATH
export PATH=$PATH:~/.local/bin            # Python(pip)用PATH
export PATH=$PATH:~/bin                   # 自作スクリプト群の配置用ディレクトリPATH

# ssh agent用のsockファイル
if [ -z "${SSH_CLIENT}" ]; then
  export SSH_AUTH_SOCK=~/.agent # ssh-agentのSOCK用PATH
fi

# Dockerコンテナ接続前後に実行するコマンド(`docker_runin`や`docker_login`で使う)
case ${OSTYPE} in
darwin*)
  export EXEC_BEFORE_DOCKER_IN='printf "\033]50;SetProfile=docker\a"'
  export EXEC_AFTER_DOCKER_IN='printf "\033]50;SetProfile=Default\a"'
  ;;
linux*)
  # TODO: Linux用のOSCエスケープシーケンスに書き換える
  export EXEC_BEFORE_DOCKER_IN='echo -ne "\e]10;#C0C0C0\a\e]11;#431030\a"'
  export EXEC_AFTER_DOCKER_IN='echo -ne "\e]10;#C0C0C0\a\e]11;#202020\a"'
  ;;
esac
